# Generated by Django 3.0.8 on 2020-07-20 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Nickname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/')),
                ('phone', models.IntegerField()),
                ('add', models.TextField()),
                ('dob', models.CharField(max_length=200)),
                ('zodiac', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('brothername', models.CharField(max_length=200)),
                ('sistername', models.CharField(max_length=200)),
                ('Bestfriendname', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('txtmail', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('Relation', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=200)),
                ('suggestions', models.TextField()),
                ('postdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
