# Generated by Django 3.0.8 on 2020-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambookapp', '0002_auto_20200720_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
